---
params:
  bus_days: 252
  bus_days_month: 22
  days_year: 365
  # ^^ insert values for crra bounds for infinite values
title: "Volatility Options / Gruenbichler and Longstaff (1996)"
author: "Erik_senn"
date: "14 03 2019"
output:
  pdf_document:
    fig_caption:        true
    fig_height:         5.5
    fig_width:          5.5
    keep_tex:           false
    number_sections:    true
    toc:                true
    toc_depth:          5
    latex_engine:       pdflatex
---

```{r preamble, echo=FALSE, include=FALSE}
# set wd
setwd("C:/Users/eriks/Documents/GitHub/QuantPortfolioMgmtPrjct/project/R")

# functions
source("functions.R")
filter <- dplyr::filter
select <- dplyr::select

# For non-nix users (as defined in `./shell.nix`)
library(tidyverse)
library(xts)
library(readxl)
library(timeSeries)
library(kableExtra) # tables•
library(skimr) # decriptive stats
library(gridExtra)
library(GGally)
library(xtable)
library(caret)
library(shape)
library(tikzDevice)
library(cleandata)
library(ggcorrplot)
library(psych)
library(Sim.DiffProc)

options(xtable.comment = FALSE, 
        digits = 6)
knitr::opts_chunk$set( dev="pdf"
                     , external=TRUE
                     , fig.width=7
                     , fig.height=4
                     , fig.path="./assets/figs/"
                     , cache=FALSE
                     , echo=FALSE
                     , warning=TRUE
                     , message=FALSE
                     , tidy=TRUE
                     , cache=TRUE
                     , fig.align="center"
                     , fig.pos="!hbt"
                     )

```

# Properties of Gruenbichler / Longstaff Volatility Option Pricing model
## Show example forward and option prices for different parameters 
```{r propertiesModel}
# define intial parameters
  # parameter names as in hilpsch, not in function in R 
  # parameters for CIR process
  v0_down = 17.5
  v0_down_extreme = 0
  v0_up = 22.5
  v0_up_extreme = 50
  vol_vol = 2
  theta = 20 
  v0 = theta # long term mean = theta 
  kappa = 0.1
  zeta = 0 # assumption: no risk premium for additional vola
  r_f = 0.01
  
  # paramters for options / fw
  K = 20
  K_up = 22.5
  K_down = 17.5
  maturity = 0.5
  
  
  # forwards
    # basic forward value
      gl96_forward(kappa, theta,maturity,v0_down)
      
    # plot forwards for different maturities and different starting values
      # calculate fw values
      mat_ex = seq(0,10,0.05)
      forward_price_1 = gl96_forward(kappa, theta,mat_ex,v0_down)
      forward_price_2 = gl96_forward(kappa, theta,mat_ex,v0_up)
      forward_price_3 = gl96_forward(kappa, theta,mat_ex,v0)
      long_run_mean = rep(theta, length(mat_ex))
      
      # plot function
      xlab = "Maturity in Years"
      ylab = "Price"
      title = "Forward Prices - Low Kappa"
      names_y = c("V0 = 17.5%", "V0 = 22.5%", "V0 = long run mean")
    
      line_plot_multiple(title=title,x=mat_ex, xlab = xlab, names_y = names_y, ylab = ylab,y1=forward_price_1, y2=forward_price_2, y3= forward_price_3)
      
    # plot forwards for different maturities and different starting values
        # calculate fw values
        mat_ex = seq(0,10,0.05)
        kappa_ex = 0.5
        forward_price_1 = gl96_forward(kappa_ex, theta,mat_ex,v0_down)
        forward_price_2 = gl96_forward(kappa_ex, theta,mat_ex,v0_up)
        forward_price_3 = gl96_forward(kappa_ex, theta,mat_ex,v0)
        long_run_mean = rep(theta, length(mat_ex))
        
        # plot function
        xlab = "Maturity in Years"
        ylab = "Price"
        title = "Forward Prices - High Kappa"
        names_y = c("V0 = 17.5%", "V0 = 22.5%", "V0 = long run mean")
      
        line_plot_multiple(title=title,x=mat_ex, xlab = xlab, names_y = names_y, ylab = ylab,y1=forward_price_1, y2=forward_price_2, y3= forward_price_3)
        
  # Call Options
    # basic call value
      gl96_call_option(kappa, zeta, theta, vol_vol, maturity, K, v0_down,r_f)
 
    # plot calls for different maturities and different starting values
      # calculate values
      mat_ex = seq(0.05,10,0.05)
      call_price_1 = gl96_call_option(kappa, zeta, theta, vol_vol, mat_ex, K, v0_down,r_f)
      call_price_2 = gl96_call_option(kappa, zeta,theta, vol_vol, mat_ex, K, v0_up,r_f)
      call_price_3 = gl96_call_option(kappa, zeta, theta, vol_vol, mat_ex, K, v0,r_f)
      
      # plot function
      xlab = "Maturity in Years"
      ylab = "Price"
      title = "Call Prices - Maturity"
      names_y = c("V0 = 17.5%", "V0 = 22.5%", "V0 = long run mean")
    
      line_plot_multiple(title=title,x=mat_ex, xlab = xlab, names_y = names_y, ylab = ylab,y1=call_price_1, y2=call_price_2, y3=call_price_3)
      
    # plot calls for CRAZY different starting values and different strikes values
      mat_ex = seq(0.05,10,0.05)
      call_price_1 = gl96_call_option(kappa, zeta, theta, vol_vol, mat_ex, K, v0_down_extreme,r_f)
      call_price_2 = gl96_call_option(kappa, zeta,theta, vol_vol, mat_ex, K, v0_up_extreme,r_f)
      call_price_3 = gl96_call_option(kappa, zeta, theta, vol_vol, mat_ex, K, v0,r_f)
      
      # plot function
      xlab = "Maturity in Years"
      ylab = "Price"
      title = "Call Prices - Extreme Start Values"
      names_y = c("V0 = 0%", "V0 = 100%", "V0 = long run mean")
    
      line_plot_multiple(title=title,x=mat_ex, xlab = xlab, names_y = names_y, ylab = ylab,y1=call_price_1, y2=call_price_2, y3=call_price_3)
      
    # plot calls for different maturities and different starting values
      # calculate values
      strikes = seq(10,30,1)
      call_price_1 = gl96_call_option(kappa, zeta, theta, vol_vol, maturity, strikes, v0_down,r_f)
      call_price_2 = gl96_call_option(kappa, zeta, theta, vol_vol, maturity, strikes, v0_up,r_f)
      call_price_3 = gl96_call_option(kappa, zeta, theta, vol_vol, maturity, strikes, v0,r_f)   
      
      # plot function
      xlab = "Strike"
      ylab = "Price"
      title = "Call Prices - Strikes"
      names_y = c("V0 = 17.5%", "V0 = 22.5%", "V0 = long run mean")
    
      line_plot_multiple(title=title,x=strikes, xlab = xlab, names_y = names_y, ylab = ylab,y1=call_price_1, y2=call_price_2, y3=call_price_3)
      
  # plot calls for different volatilities and different starting values
      # calculate values
      vol_vol_ex = seq(0.25,5,0.05)
      call_price_1 = gl96_call_option(kappa, zeta, theta, vol_vol_ex, maturity, K, v0_down,r_f)
      call_price_2 = gl96_call_option(kappa, zeta, theta, vol_vol_ex, maturity, K, v0_up,r_f)
      call_price_3 = gl96_call_option(kappa, zeta, theta, vol_vol_ex, maturity, K, v0,r_f)
      
      # plot function
      xlab = "Annual Volatility in Percent"
      ylab = "Price"
      title = "Call Prices - Volatility"
      names_y = c("V0 = 17.5%", "V0 = 22.5%", "V0 = long run mean")
    
      line_plot_multiple(title=title,x=vol_vol_ex*100, xlab = xlab, names_y = names_y, ylab = ylab,y1=call_price_1, y2=call_price_2, y3 = call_price_3)
      
      
# Put Options
    # basic put value
      call = gl96_call_option(kappa, zeta, theta, vol_vol, maturity, K, v0_down,r_f)
      future = gl96_forward(kappa, theta,maturity,v0_down)
      gl96_put_call_parity(call, "call", future, K, r_f, maturity)
      
    # plot puts for different maturities and different starting values
      # calculate values
      mat_ex = seq(0.05,10,0.05)
      call_price_1 = gl96_call_option(kappa, zeta, theta, vol_vol, mat_ex, K, v0_down,r_f)
      call_price_2 = gl96_call_option(kappa, zeta,theta, vol_vol, mat_ex, K, v0_up,r_f)
      call_price_3 = gl96_call_option(kappa, zeta, theta, vol_vol, mat_ex, K, v0,r_f)
      
      future_1 = gl96_forward(kappa, theta, mat_ex, v0_down)
      future_2 = gl96_forward(kappa, theta, mat_ex, v0_up)
      future_3 = gl96_forward(kappa, theta, mat_ex, v0)
      
      put_price_1 = gl96_put_call_parity(call_price_1, "call", future_1, K, r_f, mat_ex)
      put_price_2 = gl96_put_call_parity(call_price_2, "call", future_2, K, r_f, mat_ex)
      put_price_3 = gl96_put_call_parity(call_price_3, "call", future_3, K, r_f, mat_ex)

      
      # plot function
      xlab = "Maturity in Years"
      ylab = "Price"
      title = "Put Prices - Maturity"
      names_y = c("V0 = 17.5%", "V0 = 22.5%", "V0 = long run mean")
    
      line_plot_multiple(title=title,x=mat_ex, xlab = xlab, names_y = names_y, ylab = ylab,y1=put_price_1, y2=put_price_2, y3=put_price_3)
      
    # plot puts for CRAZY different starting values and different strikes values
      mat_ex = seq(0.05,1,0.05)
      call_price_1 = gl96_call_option(kappa, zeta, theta, vol_vol, mat_ex, K, v0_down_extreme,r_f)
      call_price_2 = gl96_call_option(kappa, zeta,theta, vol_vol, mat_ex, K, v0_up_extreme,r_f)
      call_price_3 = gl96_call_option(kappa, zeta, theta, vol_vol, mat_ex, K, v0,r_f)
      
      future_1 = gl96_forward(kappa, theta, mat_ex, v0_down_extreme)
      future_2 = gl96_forward(kappa, theta, mat_ex, v0_up_extreme)
      future_3 = gl96_forward(kappa, theta, mat_ex, v0)
      
      put_price_1 = gl96_put_call_parity(call_price_1, "call", future_1, K, r_f, mat_ex)
      put_price_2 = gl96_put_call_parity(call_price_2, "call", future_2, K, r_f, mat_ex)
      put_price_3 = gl96_put_call_parity(call_price_3, "call", future_3, K, r_f, mat_ex)
      
      # plot function
      xlab = "Maturity in Years"
      ylab = "Price"
      title = "Put Prices - Extreme Start Values"
      names_y = c("V0 = 0%", "V0 = 100%", "V0 = long run mean")
    
      line_plot_multiple(title=title,x=mat_ex, xlab = xlab, names_y = names_y, ylab = ylab,y1=put_price_1, y2=put_price_2, y3=put_price_3)
      
    # plot puts for different strikes and different starting values
      # calculate values
      strikes = seq(10,30,1)
      call_price_1 = gl96_call_option(kappa, zeta, theta, vol_vol, maturity, strikes, v0_down,r_f)
      call_price_2 = gl96_call_option(kappa, zeta, theta, vol_vol, maturity, strikes, v0_up,r_f)
      call_price_3 = gl96_call_option(kappa, zeta, theta, vol_vol, maturity, strikes, v0,r_f)   
      
      future_1 = gl96_forward(kappa, theta, maturity, v0_down)
      future_2 = gl96_forward(kappa, theta, maturity, v0_up)
      future_3 = gl96_forward(kappa, theta, maturity, v0)
      
      put_price_1 = gl96_put_call_parity(call_price_1, "call", future_1, strikes, r_f, maturity)
      put_price_2 = gl96_put_call_parity(call_price_2, "call", future_2, strikes, r_f, maturity)
      put_price_3 = gl96_put_call_parity(call_price_3, "call", future_3, strikes, r_f, maturity)
      
      # plot function
      xlab = "Strike"
      ylab = "Price"
      title = "Put Prices - Strikes"
      names_y = c("V0 = 17.5%", "V0 = 22.5%", "V0 = long run mean")
      
      line_plot_multiple(title=title,x=strikes, xlab = xlab, names_y = names_y, ylab = ylab, y1=put_price_1, y2=put_price_2, y3=put_price_3)
      
    # plot puts for different volatilities and different starting values
      # calculate values
      vol_vol_ex = seq(0.25,5,0.05)
      call_price_1 = gl96_call_option(kappa, zeta, theta, vol_vol_ex, maturity, K, v0_down,r_f)
      call_price_2 = gl96_call_option(kappa, zeta, theta, vol_vol_ex, maturity, K, v0_up,r_f)
      call_price_3 = gl96_call_option(kappa, zeta, theta, vol_vol_ex, maturity, K, v0,r_f)
      
      future_1 = gl96_forward(kappa, theta, maturity, v0_down)
      future_2 = gl96_forward(kappa, theta, maturity, v0_up)
      future_3 = gl96_forward(kappa, theta, maturity, v0)
      
      put_price_1 = gl96_put_call_parity(call_price_1, "call", future_1, K, r_f, maturity)
      put_price_2 = gl96_put_call_parity(call_price_2, "call", future_2, K, r_f, maturity)
      put_price_3 = gl96_put_call_parity(call_price_3, "call", future_3, K, r_f, maturity)
      
      # put plot function
      xlab = "Annual Volatility in Percent"
      ylab = "Price"
      title = "Put Prices - Volatility"
      names_y = c("V0 = 17.5%", "V0 = 22.5%", "V0 = long run mean")
    
      line_plot_multiple(title=title,x=vol_vol_ex*100, xlab = xlab, names_y = names_y, ylab = ylab,y1=put_price_1, y2=put_price_2, y3 = put_price_3)
      

```

## Simulation Option Values

```{r monteCarloTest}
# parameters for one day
kappa = 0.1
theta = 20
maturity = 0.5
zeta = 0
vol_vol = 2
K = seq(0:40)
maturity = 0.5
v0_down = 17.5
r_f = 0.01


# theoretical prices to compare
  forward_model = gl96_forward(kappa, theta,maturity,v0_down)
  call_eu_model = gl96_call_option(kappa, zeta, theta, vol_vol, maturity, K, v0_down,r_f)
  put_eu_model = gl96_put_call_parity(call_eu_model, "call", forward_model, K, r_f, maturity)


 # parameters for Monte Carlo 
  size_process = 200
  size_process_with_start = size_process+1
  number_trajectories = 1000

  # simulate CIR-trajactories
  vol_simulated = cir_simulation_milstein(kappa,theta,vol_vol,v0_down,maturity,size_process, number_trajectories)
  
  # plot first 10 trajectories
  data_x = seq(maturity/size_process_with_start, maturity, maturity/size_process_with_start)
  xlab = "Time"
  ylab = "Volatility"
  title = "Simulated Volatlity Paths"
  names_y = c("a","b","c","d","e","f","g","h") # to get colors
  legend = FALSE
  
  line_plot_multiple(title=title,x=data_x,names_y=names_y, legend = legend, xlab = xlab, ylab = ylab, y1=vol_simulated[,1], y2=vol_simulated[,2], y3=vol_simulated[,3], y4=vol_simulated[,4], y5=vol_simulated[,5], y6=vol_simulated[,6], y7=vol_simulated[,7], y8=vol_simulated[,8], y9=vol_simulated[,9], y10=vol_simulated[,10])

  
  
# calculate option values
  # initialze data frame. Only need last value of trajectories
    monte_carlo_european = as.data.frame(vol_simulated[size_process_with_start,])
    colnames(monte_carlo_european) = c("Vol_in_T")
      
      # Normal European Options
        # loop over all strikes and calculate payoffs
        monte_carlo_european$payoff_call_eu = pmax(monte_carlo_european$Vol_in_T-K,0)
        monte_carlo_european$payoff_put_eu = pmax(K-monte_carlo_european$Vol_in_T,0)
      
      call_eu_sim = mean(monte_carlo_european$payoff_call_eu*exp(-r_f*maturity))
      put_eu_sim =  mean(monte_carlo_european$payoff_put_eu*exp(-r_f*maturity))
      
      # Barrier Options (end)
      knock_out_call = 25
      knock_in_call = 25
      knock_out_put = 15
      knock_in_put = 15
      
      # knock out options
        monte_carlo_european$payoff_call_ko  = monte_carlo_european$payoff_call_eu
        monte_carlo_european$payoff_call_ko[monte_carlo_european$payoff_call_eu+K>knock_out_call] = 0 
        
        monte_carlo_european$payoff_put_ko  = monte_carlo_european$payoff_put_eu
        monte_carlo_european$payoff_put_ko[K-monte_carlo_european$payoff_put_eu<knock_out_put] = 0 
      
      # knock in options
        monte_carlo_european$payoff_call_ki  = monte_carlo_european$payoff_call_eu
        monte_carlo_european$payoff_call_ki[monte_carlo_european$payoff_call_eu+K<knock_in_call] = 0 
        
        monte_carlo_european$payoff_put_ki  = monte_carlo_european$payoff_put_eu
        monte_carlo_european$payoff_put_ki[K-monte_carlo_european$payoff_put_eu>knock_in_put] = 0 
      
      call_ko_sim = mean(monte_carlo_european$payoff_call_ko*exp(-r_f*maturity))
      put_ko_sim =  mean(monte_carlo_european$payoff_put_ko*exp(-r_f*maturity))
      call_ki_sim = mean(monte_carlo_european$payoff_call_ki*exp(-r_f*maturity))
      put_ki_sim =  mean(monte_carlo_european$payoff_put_ki*exp(-r_f*maturity))
      
      call_ko_sim
      call_ki_sim
      call_ko_sim+call_ki_sim
      call_eu_sim
      call_eu_model
      
      put_ko_sim
      put_ki_sim
      put_ko_sim+put_ki_sim
      put_eu_sim
      put_eu_model
      
############# ISSUE AM OPTIONS
      
  # American Options
      monte_carlo_american = as.data.frame(vol_simulated)
      i = c(1:size_process_with_start)-1
      time_to_maturity = (size_process-i)/size_process*maturity
      disFactor = exp(-r_f*i/size_process_with_start*maturity)
      monte_carlo_american_call_po = pmax((monte_carlo_american-K)*disFactor,0)
      
      monte_carlo_american_call_intrinsic =  matrix(data=NA, nrow=nrow(monte_carlo_american_call_po), ncol = ncol(monte_carlo_american_call_po))
      
      # 
      # for (i in 1:number_trajectories) {
      # monte_carlo_american_call_intrinsic[,i] = gl96_call_option(kappa, zeta, theta, vol_vol, T_call= time_to_maturity, K, current_value_underlying = monte_carlo_american[,i],r_f) # issue with time to maturity 0
      # }
      
  # Compare to Model values 
      print("Call model")
      call_eu_model
      print("call Monte Carlo")
      call_eu_sim
      print("Put model")
      put_eu_model
      print("Put Monte Carlo")
      put_eu_sim

```

# Simulation plot GBM and CIR for intro Vola slide
```{r simulateGeometricBrownianMotion}
# define paramters for simulations
S_0 = 20
mu_gmb = 0.02
sigma_gbm =0.2
maturity = 10
size_process = 1000
size_process_with_start = size_process+1
number_trajectories = 1000

simulated_gbm = geometric_brownian_motion(Xzero = S_0, mu=mu_gmb, sigma =sigma_gbm, T= maturity, size_process = size_process, number_trajectories = number_trajectories) 
  

 # plot first 10 trajectories
  data_x = seq(maturity/size_process_with_start, maturity, maturity/size_process_with_start)
  xlab = "Time"
  ylab = "Stock Price"
  title = "Geometric Brownian Motion Paths"
  names_y = c("a","b","c","d","e","f","g","h") # to get colors
  legend = FALSE
  
  line_plot_multiple(title=title,x=data_x,names_y=names_y, legend = legend, xlab = xlab, ylab = ylab, y1=simulated_gbm[,1], y2=simulated_gbm[,2], y3=simulated_gbm[,3], y4=simulated_gbm[,4])
  
  
  # simulate CIR-trajactories
  vol_simulated = cir_simulation_milstein(kappa,theta,sigma_gbm,S_0,maturity,size_process, number_trajectories)
  
  # plot first 10 trajectories
  data_x = seq(maturity/size_process_with_start, maturity, maturity/size_process_with_start)
  xlab = "Time"
  ylab = "Volatility"
  title = "Cox-Ingersoll-Ross Paths"
  names_y = c("a","b","c","d","e","f","g","h") # to get colors
  legend = FALSE
  
  line_plot_multiple(title=title,x=data_x,names_y=names_y, legend = legend, xlab = xlab, ylab = ylab, y1=vol_simulated[,1], y2=vol_simulated[,2], y3=vol_simulated[,3], y4=vol_simulated[,4])  

```

